### ISSUE TITLE
ログに出力してるスタックトレースで発生箇所が元ファイルの何行目かわからない

### ISSUE THREAD

**Issue by azmint** [LearnDDD/task-manager-api#7]
サンプルスタックトレース
```
TypeError: sample
    at MySQLTaskRepository.generateID (/Users/roppongiyuuki/Documents/DDD神戸支社/task-manager-api/dist/server.js:666:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CreateTaskService.execute (/Users/roppongiyuuki/Documents/DDD神戸支社/task-manager-api/dist/server.js:162:22)
    at async CreateTaskController.execute (/Users/roppongiyuuki/Documents/DDD神戸支社/task-manager-api/dist/server.js:1022:33)
```

**Comment by azmint** [comment]
server.jsに全部まとめるんじゃなくて、元ファイル名と同じjsファイルを生成する方法があるかも
